import type { Customer } from '../src/types.ts';
const base = {
  plan: 'Northstar Plus · monthly',
  dueDate: '2026-10-01',
  attempts: 0,
  paymentStatus: 'outstanding' as const,
  recoveryStatus: 'ready' as const,
  optedOut: false,
  reviewReason: null,
  callbackAt: null,
};
export const customers: Customer[] = [
  {
    id: 'C001',
    name: 'Aanya Rao',
    initials: 'AR',
    email: 'aanya@example.test',
    amount: 149900,
    failure: 'Insufficient funds',
    failureCode: 'INSUFFICIENT_FUNDS',
    description:
      'The gateway reported insufficient funds for this monthly renewal. Ask whether a one-off payment would help.',
    recommendation: 'Offer a secure payment link',
    scenario: 'pay_now',
    scenarioLabel: 'Ready to pay',
  },
  {
    id: 'C002',
    name: 'Kabir Shah',
    initials: 'KS',
    email: 'kabir@example.test',
    amount: 299900,
    failure: 'Card expired',
    failureCode: 'CARD_EXPIRED',
    description:
      'The saved card has expired. A one-off payment can recover this invoice; future autopay needs a payment-method update.',
    recommendation: 'Recover invoice, flag card update',
    scenario: 'expired_card',
    scenarioLabel: 'Expired card',
  },
  {
    id: 'C003',
    name: 'Meera Iyer',
    initials: 'MI',
    email: 'meera@example.test',
    amount: 99900,
    failure: 'Bank unavailable',
    failureCode: 'BANK_UNAVAILABLE',
    description:
      'The gateway reported a temporary bank failure. Do not invent the bank’s internal cause or automatically retry a debit.',
    recommendation: 'Explain and offer an alternative',
    scenario: 'bank_error',
    scenarioLabel: 'Temporary failure',
  },
  {
    id: 'C004',
    name: 'Rohan Das',
    initials: 'RD',
    email: 'rohan@example.test',
    amount: 199900,
    failure: 'Mandate revoked',
    failureCode: 'MANDATE_REVOKED',
    description:
      'The recurring mandate was revoked. New authorization requires a merchant-owned flow. Pause recovery and request review.',
    recommendation: 'Request merchant review',
    scenario: 'mandate_revoked',
    scenarioLabel: 'Mandate review',
  },
  {
    id: 'C005',
    name: 'Sana Khan',
    initials: 'SK',
    email: 'sana@example.test',
    amount: 149900,
    failure: 'Payment declined',
    failureCode: 'DECLINED',
    description:
      'The payment was declined. Respect the customer’s timing and record a callback only when requested.',
    recommendation: 'Find a convenient callback time',
    scenario: 'callback',
    scenarioLabel: 'Call back later',
  },
  {
    id: 'C006',
    name: 'Arjun Menon',
    initials: 'AM',
    email: 'arjun@example.test',
    amount: 399900,
    failure: 'Payment declined',
    failureCode: 'DECLINED',
    description:
      'The ledger still shows this payment as outstanding. A claim of prior payment must be reconciled by the merchant.',
    recommendation: 'Reconcile before collecting again',
    scenario: 'already_paid',
    scenarioLabel: 'Already paid claim',
  },
  {
    id: 'C007',
    name: 'Nisha Patel',
    initials: 'NP',
    email: 'nisha@example.test',
    amount: 99900,
    failure: 'Payment declined',
    failureCode: 'DECLINED',
    description:
      'The customer may request no further contact. Persist an opt-out immediately, even before conversational consent.',
    recommendation: 'Respect contact preferences',
    scenario: 'opt_out',
    scenarioLabel: 'Stop contact',
  },
  {
    id: 'C008',
    name: 'Dev Kapoor',
    initials: 'DK',
    email: 'dev@example.test',
    amount: 249900,
    failure: 'Payment declined',
    failureCode: 'DECLINED',
    description:
      'The customer may dispute this invoice. Pause automated recovery and record an unresolved billing review.',
    recommendation: 'Listen and route to a person',
    scenario: 'dispute',
    scenarioLabel: 'Billing dispute',
  },
  {
    id: 'C009',
    name: 'Tara Sen',
    initials: 'TS',
    email: 'tara@example.test',
    amount: 199900,
    failure: 'Payment declined',
    failureCode: 'DECLINED',
    description:
      'A cancellation request requires merchant review. Recording the request is not confirmation that the subscription was cancelled.',
    recommendation: 'Record a cancellation request',
    scenario: 'cancel',
    scenarioLabel: 'Cancellation request',
  },
  {
    id: 'C010',
    name: 'Vikram Joshi',
    initials: 'VJ',
    email: 'vikram@example.test',
    amount: 149900,
    failure: 'Payment declined',
    failureCode: 'DECLINED',
    description:
      'No response or declined permission should end the attempt. Do not fabricate consent or automatically redial.',
    recommendation: 'End politely; leave payment unchanged',
    scenario: 'no_answer',
    scenarioLabel: 'No answer / not now',
  },
].map((c) => ({ ...base, ...c }));
